FROM ksoichiro/freeswitch

MAINTAINER Clint Berry "clint@getweave.com"

COPY conf/autoload_configs/sofia.conf.xml /etc/freeswitch/autoload_configs/sofia.conf.xml
COPY conf/sip_profiles/internal.xml /etc/freeswitch/sip_profiles/internal.xml

EXPOSE 5060
EXPOSE 5080

